### ISSUE TITLE
Duplicated Repository for API-M Cloud Formation Templates

### ISSUE THREAD

**Issue by imesh** [wso2/aws-apim#13]
What would be the reason for creating a new repository for maintaining WSO2 API Manager Cloud Formation Templates while already having another?
https://github.com/wso2/cloudformation-apim

**Comment by ctienshi** [comment]
@imesh Since we are creating installation resources for AWS platform, we thought of going with the repository name "aws-apim". Cloudformation is just the technology and we are not planning on creating AWS resources using any other technology such as Teraform or any other. Therefore the most suitatable repo name would be aws-apim.
